<script setup lang="ts">
import {
  ArrowRight,
  ArrowUpRight,
  Bot,
  Box,
  Check,
  ChevronDown,
  Code,
  Compass,
  Cpu,
  FileSearch,
  Gauge,
  Globe,
  Handshake,
  Image,
  LayoutDashboard,
  Library,
  LifeBuoy,
  Mail,
  Menu,
  MessageSquare,
  Mic,
  Minus,
  Music,
  Package,
  PenTool,
  Phone,
  Plug,
  Plus,
  Repeat,
  ScanSearch,
  Server,
  Shield,
  Sparkles,
  Terminal,
  Truck,
  Users,
  Video,
  WifiOff,
  Wrench,
  X,
} from "lucide-vue-next";

const icons = {
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  bot: Bot,
  box: Box,
  check: Check,
  "chevron-down": ChevronDown,
  code: Code,
  compass: Compass,
  cpu: Cpu,
  "file-search": FileSearch,
  gauge: Gauge,
  globe: Globe,
  handshake: Handshake,
  image: Image,
  layout: LayoutDashboard,
  library: Library,
  lifebuoy: LifeBuoy,
  mail: Mail,
  menu: Menu,
  message: MessageSquare,
  mic: Mic,
  minus: Minus,
  music: Music,
  package: Package,
  pen: PenTool,
  phone: Phone,
  plug: Plug,
  plus: Plus,
  repeat: Repeat,
  scan: ScanSearch,
  server: Server,
  shield: Shield,
  sparkles: Sparkles,
  terminal: Terminal,
  truck: Truck,
  users: Users,
  video: Video,
  "wifi-off": WifiOff,
  wrench: Wrench,
  x: X,
} as const;

const props = withDefaults(defineProps<{ name: string; size?: number; strokeWidth?: number }>(), {
  size: 20,
  strokeWidth: 1.75,
});

const component = computed(() => icons[props.name as keyof typeof icons] ?? Sparkles);
</script>

<template>
  <component :is="component" :size="size" :stroke-width="strokeWidth" aria-hidden="true" />
</template>
